#!/usr/bin/bash
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# clean up
rm -rf /home/admin/.[^.]*
rm -rf /root/*
sm-prepare-image -y
